### ISSUE TITLE
Surface viewport at top level

### ISSUE THREAD

**Issue by rpearl** [chlorophyll/chlorophyll#110]
There's a few different things which require explicit interaction with the viewport:
- 2d axes overlay
- click events / etc for various selection tools.

Right now things that need it can escape-hatch into it by looking at the `#viewport` DOM element, but probably the viewport should be accessible as a top-level vue object that overlays can be attached to using a method instead.

**Comment by cwill** [comment]
Ideally, we'd be able to create short-lived views for menus and dialogs (e.g. it'd be nice if mapping configs could have a display of the orthogonal projection in addition to the main perspective viewport).
