### ISSUE TITLE
Pixel-pushing backend

### ISSUE THREAD

**Issue by cwill** [chlorophyll/chlorophyll#36]

**Comment by rpearl** [comment]
The goal here is to have as little non-intuitive configuration as possible.

Here's something that I think is viable and pretty close to ideal:
- Flash an image on an SD card for a raspberry pi 3 and plug it in
- Connect to the Chlorophyll hotspot the pi3 creates
- In some way (either "go to this url" or heck, maybe even a captive portal or piggybacking the "sign-in" flow on that hotspot) pop up a Chlorophyll configuration page where you can name the artpiece, upload a Chlorophyll save file, set admin passwords, wire up data sources, etc.

**Comment by cwill** [comment]
(backend is in flux but exists and works)
