### ISSUE TITLE
Consider adding alpha values to mappings

### ISSUE THREAD

**Issue by rpearl** [chlorophyll/chlorophyll#49]
Discussing object mappings (#48), it came to light that instead of a binary decision ("this point is mapped, this point is not"), it might be sensible to have opacity values instead, representing "how much" a point is in a space. The color value produced by the pattern would then be modulated by the opacity for that point.

**Comment by cwill** [comment]
I think we've resolved at this point that it's more useful to have mappings be discrete and handle any fuzziness with masking/blending/mixing.
