### ISSUE TITLE
Projection mappings: fix snapshot state for plane origin and refactor setFromCamera()

### ISSUE THREAD

**Issue by cwill** [chlorophyll/chlorophyll#97]
If the window changes size, the widget will have moved, so it doesn't make sense to use the screen position of the widget as the representative state - the absolute 3d position is the important piece of information.

This leads to: always setting a projection mapping via the camera is very nonideal - setting it should take some parameters, which can optionally be provided from the camera.

**Comment by rpearl** [comment]
Fixed in Vue rewrite?
